# Copyright 2018 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "io.projectriff.riff"
name = "riff Buildpack"
version = "1.0.0-BUILD-SNAPSHOT"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.dependencies]]
id      = "riff-invoker-java"
name    = "riff Java Invoker"
version = "0.1.3"
uri     = "https://repo.spring.io/libs-snapshot-local/io/projectriff/java-function-invoker/0.1.3-SNAPSHOT/java-function-invoker-0.1.3-20181114.211611-3-exec.jar"
sha256  = "43158dcd74ad379d6ca2c02ff26734ff00c204ca552e00218d3abdfd2ffce6e0"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/java-function-invoker/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "riff-invoker-command"
name    = "riff Command Invoker"
version = "0.0.8"
uri     = "https://storage.googleapis.com/projectriff/command-function-invoker/command-function-invoker-linux-amd64-0.0.8.tgz"
sha256  = "cf475eae3043cf7dc0818b5ccd70f99c9542d798160fa3965c8506787a70e8d3"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/command-function-invoker/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "riff-invoker-node"
name    = "riff Node Invoker"
version = "0.1.0+snapshot"
uri     = "https://storage.googleapis.com/projectriff/node-function-invoker/releases/v0.1.0-snapshot/snapshots/node-function-invoker-0.1.0-snapshot-49db1d7a8b32a61bea0d152cbb817a4e0ca171a3.tgz"
sha256  = "d0dbef29bd0ddb9c88cf85dd51333226b3dd3393c0ab9d8a836b671499b70dee"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/node-function-invoker/blob/master/LICENSE"



[metadata]
  pre_package = "ci/build.sh"
  include_files = [
    "LICENSE",
    "NOTICE",
    "README.md",
    "bin/build",
    "bin/detect",
    "buildpack.toml",
  ]
