# Copyright 2018 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "io.projectriff.riff"
name = "riff Buildpack"
version = "1.0.0-BUILD-SNAPSHOT"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.dependencies]]
id      = "riff-invoker-java"
name    = "riff Java Invoker"
version = "0.1.2"
uri     = "https://repo.spring.io/libs-milestone-local/io/projectriff/java-function-invoker/0.1.2/java-function-invoker-0.1.2-exec.jar"
sha256  = "dd0e4ef2c140d29900e4e9b549f017d78b0fafaa1974c73f512fe25d0dca878e"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/java-function-invoker/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "riff-invoker-command"
name    = "riff Command Invoker"
version = "0.0.8+snapshot"
uri     = "https://storage.googleapis.com/projectriff/command-function-invoker/command-function-invoker-linux-amd64-0.0.8-ef49924de13f0ccee7e29584dcdc69485f30c121.tgz"
sha256  = "782cf12324db18bcb020449b527fd23d1dcb11334792feabeb38ac79a9d0d58b"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/command-function-invoker/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "riff-invoker-node"
name    = "riff Node Invoker"
version = "0.1.0+snapshot"
uri     = "https://storage.googleapis.com/projectriff/node-function-invoker/releases/v0.1.0-snapshot/snapshots/node-function-invoker-0.1.0-snapshot-49db1d7a8b32a61bea0d152cbb817a4e0ca171a3.tgz"
sha256  = "d0dbef29bd0ddb9c88cf85dd51333226b3dd3393c0ab9d8a836b671499b70dee"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/projectriff/node-function-invoker/blob/master/LICENSE"



[metadata]
  pre_package = "ci/build.sh"
  include_files = [
    "LICENSE",
    "NOTICE",
    "README.md",
    "bin/build",
    "bin/detect",
    "buildpack.toml",
  ]
